"""add group memory

迁移 ID: 811f4ae4bcd1
父迁移: 2ba09dd95dc6
创建时间: 2026-03-31 16:08:32.834210

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '811f4ae4bcd1'
down_revision: str | Sequence[str] | None = '2ba09dd95dc6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imitater_llm_groupmemory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('msg_count_at_last_update', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imitater_llm_groupmemory')),
    info={'bind_key': 'imitater_llm'}
    )
    with op.batch_alter_table('imitater_llm_groupmemory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imitater_llm_groupmemory_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_imitater_llm_groupmemory_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imitater_llm_groupmemory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imitater_llm_groupmemory_updated_at'))
        batch_op.drop_index(batch_op.f('ix_imitater_llm_groupmemory_session_id'))

    op.drop_table('imitater_llm_groupmemory')
    # ### end Alembic commands ###
